// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDpCIF8IK0XHBmoz9_q7KlL1f4N6qxEeTs',
    appId: '1:923889882065:web:ff5c7334728024df6306f0',
    messagingSenderId: '923889882065',
    projectId: 'chat-scolar',
    authDomain: 'chat-scolar.firebaseapp.com',
    storageBucket: 'chat-scolar.firebasestorage.app',
    measurementId: 'G-JLQJ5T2HNM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDeItg3rGF_ua9RVVW84C3SWyVj5IfgYqA',
    appId: '1:923889882065:android:906795215d975a946306f0',
    messagingSenderId: '923889882065',
    projectId: 'chat-scolar',
    storageBucket: 'chat-scolar.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBeS-JEqJlTiBucye_onoGfbE0htjDy8tg',
    appId: '1:923889882065:ios:de1d2391b14734336306f0',
    messagingSenderId: '923889882065',
    projectId: 'chat-scolar',
    storageBucket: 'chat-scolar.firebasestorage.app',
    iosBundleId: 'com.example.chatScolar',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBeS-JEqJlTiBucye_onoGfbE0htjDy8tg',
    appId: '1:923889882065:ios:de1d2391b14734336306f0',
    messagingSenderId: '923889882065',
    projectId: 'chat-scolar',
    storageBucket: 'chat-scolar.firebasestorage.app',
    iosBundleId: 'com.example.chatScolar',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDpCIF8IK0XHBmoz9_q7KlL1f4N6qxEeTs',
    appId: '1:923889882065:web:4e93aab11dc673776306f0',
    messagingSenderId: '923889882065',
    projectId: 'chat-scolar',
    authDomain: 'chat-scolar.firebaseapp.com',
    storageBucket: 'chat-scolar.firebasestorage.app',
    measurementId: 'G-ET27MVVYHC',
  );
}
